name       : font-weather-icons
version    : 2.0.12
release    : 2
source     :
    - https://github.com/erikflowers/weather-icons/archive/refs/tags/2.0.12.tar.gz : e6a0693ec10ba423f26b7e6abcbf67ea7bec69fc0afaabb0ddd62799cdc91223
license    : OFL-1.1
component  :
    - otf  : desktop.font
    - ttf  : desktop.font
summary    :
    - Icon font with 222 weather themed icons inspired by Font Awesome (opentype)
    - ttf  : Icon font with 222 weather themed icons inspired by Font Awesome (truetype)
description: |
    Weather Icons is the only icon font with 222 weather themed icons, ready to be dropped right into any project that needs high quality weather, maritime, and meteorological based icons!
patterns   :
    - otf  : /usr/share/fonts/opentype
    - ttf  : /usr/share/fonts/truetype
replaces   :
    - ttf  : font-ibm-plex
install    : |
    install -D -m00644 _docs/font-source/weathericons-*.otf -t $installdir/usr/share/fonts/opentype/weathericons/
    install -D -m00644 font/weathericons-*.ttf -t $installdir/usr/share/fonts/truetype/weathericons/
