name       : font-weather-icons
version    : 2.0.10
release    : 1
source     :
    - https://github.com/erikflowers/weather-icons/archive/2.0.10.tar.gz : 51fc93425a61754b34ce298158de28984ad5904e58d42bbfc225704edde20d02
license    : OFL-1.1
component  : desktop.font
summary    : Icon font with 222 weather themed icons inspired by Font Awesome 
description: |
    Weather Icons is the only icon font with 222 weather themed icons, ready to be dropped right into any project that needs high quality weather, maritime, and meteorological based icons!
install    : |
    install -D -m00644 _docs/font-source/weathericons-*.otf -t $installdir/usr/share/fonts/opentype/weathericons/
    install -D -m00644 font/weathericons-*.ttf -t $installdir/usr/share/fonts/truetype/weathericons/
